### ISSUE TITLE
Video continue play after stop or hide activity

### ISSUE THREAD

**Issue by mdtuyen** [rubensousa/PreviewSeekBar#10]
Video continue play after stop or hide activity

**Comment by rubensousa** [comment]
Please, explain. This seems like a sample issue and not a library one though.

**Comment by mdtuyen** [comment]
I installed sample.
When the video is playing, 
click pause => the sound contine
click home button to hiden activity => the sound continue.

**Comment by rubensousa** [comment]
Should be fixed now: https://github.com/rubensousa/PreviewSeekBar/commit/6f9887ade96f7324329c7b0c14144e455201fb6a
