### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by sethchhim** [rubensousa/PreviewSeekBar#11]
I am trying to implement this seekbar in a rtl mode. Everything works fine but the thumbnail does not align with the seekbar button. The two are inverted: if the seekbar progress is left, the thumbnail is on the right, and vice versa.

Here is what I am using:
`previewSeekBar.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);`

Any help would be appreciated, thanks!

**Comment by rubensousa** [comment]
Will check this as soon as I have more time.

**Comment by rubensousa** [comment]
Can you check https://github.com/rubensousa/PreviewSeekBar/commit/6aacf0ffd102329ffb65cc1365c2464915879c1d?

It should work.

**Comment by sethchhim** [comment]
6aacf0f fixed it for me. Thank you for the quick response!
