### ISSUE TITLE
Too may memory used when apply this library.

### ISSUE THREAD

**Issue by mdtuyen** [rubensousa/PreviewSeekBar#14]
I apply this library and check that it make so many memory:

Before: ~60MB
After: ~315MB

Please help me how to improve the memory for my application

**Comment by rubensousa** [comment]
Are you closing the SimpleExoPlayer instance when the preview is hidden? Memory usage seems fine in the sample

**Comment by rubensousa** [comment]
Please, check the newest version and the thumbnail fetching with Glide.
