### ISSUE TITLE
intergrate PreviewSeekBar without EXOPlayer

### ISSUE THREAD

**Issue by fantasyado** [rubensousa/PreviewSeekBar#15]
hi ,your library is pretty cool, i want to use it in my own project without EXOPlayer, I've read READ_ME and haven't figured out how to do it ,you said  Create a PreviewLoader and pass it to PreviewSeekBarLayout  but i  don't  know  where i should  load preview to,should i pass PreviewSeekBarLayout instance to PreviewLoaderImpl  ?     any  help is appreciated ,  thanks in advance

**Comment by rubensousa** [comment]
PreviewLoaderImpl should have a reference to an ImageView or some other View and a reference to the source of video from which you grab the preview.

**Comment by fantasyado** [comment]
got it  ,  thanks  ;)
