### ISSUE TITLE
How to create the seekpreview thumbnail?

### ISSUE THREAD

**Issue by asrma7** [rubensousa/PreviewSeekBar#18]
How do we create the seekpreview thumbnail?
Do we have to screenshot every 5 minutes and join them to make a single image or is there any way to do so?

**Comment by rubensousa** [comment]
You need to generate them on your server side. I don't know exactly which tools you should be using for this because in my case I already had access to the sprites inside a json file. Take a look at this: https://github.com/flavioribeiro/video-thumbnail-generator

**Comment by AshishPsaini** [comment]
for local videos, how to do this.

**Comment by AshishPsaini** [comment]
I think if we are not able to create a video thumbnail sprite, this is useless. Please help how to do this with the help of glide.
