### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Angelk90** [rubensousa/PreviewSeekBar#19]
@rubensousa : 
Hi, first of all I wanted to congratulate you.

Let's start with the questions:

1) would it be possible to use the latest version of exoplayer? 2.8.1
2) if I wanted to change the graphics of the exoplayer, would it be possible?
if yes, how can I do?
3) I tried to install the module but I did not understand, I also looked at the sample folder, but it seems that something escapes me.

After creating a new project I have:
- I opened the build.gradle file and installed the dependencies:
implementation 'com.github.rubensousa: previewseekbar: 1.2'
implementation 'com.github.rubensousa: previewseekbar-exoplayer: 2.6.0'

from what I understand use glide, so I must also install Glide's addiction, right?

**Comment by Angelk90** [comment]
@rubensousa : This is the graphics I'm making:
https://drive.google.com/file/d/1AdGrMFLHxR3xi32uA3IKB7AUXElHXTQa/view

If you could give an example of the use of the PreviewSeekBar with exoplayer, you would be a pleasure.

**Comment by Angelk90** [comment]
@rubensousa : I did not find it in the readme file about it, but looking at the code I had this doubt, to have the preview of the seekBarTime I have to have a thumbnail sprite?
If I do not have it, it does not work?

If you could give an example of the use of the PreviewSeekBar with exoplayer, you would be a pleasure.

**Comment by rubensousa** [comment]
1. I'm currently updating the library to support exoplayer 2.8.1 but you shouldn't have any problems using it already.

2. What do you mean by graphics? The player controls? If so, just check the ExoPlayer docs.

3. What's exactly your issue? I'll try to improve the readme on the next release.

You need the thumbnail sprite if you want to use Glide to load the images like in the sample app. Just clone it and check it out.

**Comment by rubensousa** [comment]
You can, but you can't re-use the sample's code. You would need to do your own preview logic. You could generate the previews inside the app by storing the frames yourself.

**Comment by Angelk90** [comment]
@rubensousa :  How? Could you give me a hand? It would be very important to me. I tried on stackoverflow but nothing.

**Comment by Angelk90** [comment]
@rubensousa : This is what I managed to do: https://drive.google.com/file/d/1-rtEq37cryv9I5aKW_rv--jLiDZa_QRA/view

As you can see you do not see the preview, because I do not have a thumbnails of images.

**Comment by Angelk90** [comment]
@rubensousa : This is what I managed to do: https://drive.google.com/file/d/1-rtEq37cryv9I5aKW_rv--jLiDZa_QRA/view

As you can see you do not see the preview, because I do not have a thumbnails of images.

**Comment by rubensousa** [comment]
If you don't have those, you could try creating a mini player that simply plays an extremely low quality stream in the thumbnail view. This is how the previous sample worked. But it won't be smooth

**Comment by Angelk90** [comment]
@rubensousa : In the ExoPlayerManager.java file I was trying to modify the loadPreview method like so:
```
@Override
    public void loadPreview(long currentPosition, long max) {
        player.setPlayWhenReady(true);

        MediaMetadataRetriever retriever = new MediaMetadataRetriever();
        retriever.setDataSource(thumbnailsUrl, new HashMap<String, String>());
        Bitmap image = retriever.getFrameAtTime(2*1000000, MediaMetadataRetriever.OPTION_CLOSEST_SYNC);
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        image.compress(Bitmap.CompressFormat.PNG, 100, stream);
        GlideApp.with(context)//imageView
                .load(stream.toByteArray())
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .into(imageView);
}
```

but it does not work, crash and it does not give me the reason why it crashes.

Could you give me a hand?

**Comment by rubensousa** [comment]
This library isn't opinionated about the way you actually perform the video previews, so I'm closing this. Sorry for the late reply.
