### ISSUE TITLE
Issue: quite slow getting the image in the sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [rubensousa/PreviewSeekBar#2]
When I drag to seek, it's not immediate at all. It takes about 1-2 seconds to show the preview (tested on Nexus 5x). How come?

Also not sure what the "local" does.

**Comment by rubensousa** [comment]
The sample just contains an example of how to use it with ExoPlayer. It's not the perfect solution, that's why I created the section "Improvements" in the Readme: https://github.com/rubensousa/PreviewSeekBar#improvements

The point of open sourcing this library was releasing the morphing view and getting ideas for better solutions on how to download the video thumbnails.

Local opens an Activity to test the PreviewSeekBar with a simple view.

**Comment by AndroidDeveloperLB** [comment]
But in the screenshots it's much faster. Why didn't you use it here too?

**Comment by rubensousa** [comment]
I did, the sample is the same. Just different network conditions.

**Comment by rubensousa** [comment]
I'll close this since I've answered your question. If you come up with a better solution for loading the thumbnails, let me know.

**Comment by AndroidDeveloperLB** [comment]
Network conditions? I have a good internet connection.
How about putting a short video inside the library, instead?

**Comment by rubensousa** [comment]
I'll try to find a shorter one, but this doesn't solve the slow loading problem.

**Comment by AndroidDeveloperLB** [comment]
How come it works fine for you on the gif-screenshot on the repo main page? It seems smooth there...

**Comment by rubensousa** [comment]
Like I said, my guess is different network conditions (latency or server with high load, I don't know). It works faster in my emulator.

**Comment by AndroidDeveloperLB** [comment]
Can you please add a way inside the project, to show a built in video, so that it will be possible to know if that's really the cause to this issue ? The video file could even be on the device instead of inside the app.

**Comment by rubensousa** [comment]
Yes, I can do that. I'll replace the current local action to load a video from the storage.
I'll close this once I replace the current stream with a better one.

**Comment by AndroidDeveloperLB** [comment]
Close what?
I don't understand.

**Comment by rubensousa** [comment]
This issue. Since local playback doesn't have to do with it.

**Comment by AndroidDeveloperLB** [comment]
Why close it? We don't know for sure what's the reason for it being slow. I asked if you can use a local file, to check if the issue is because of slow connection or not.

**Comment by rubensousa** [comment]
Nevermind, I just re-read the issue title and it makes sense to keep it open. Sorry for the misunderstanding.

**Comment by kford55** [comment]
There are two gifs in the README, the fast one is google play movies, the slower one is this library. Just make sure you're comparing against the right one :)

**Comment by AndroidDeveloperLB** [comment]
@kford55 Oh, so you say it's because of using a server that has a good connection, not just the client (and I have a good connection and a good phone).

**Comment by kford55** [comment]
@AndroidDeveloperLB nope just making sure that you are comparing the correct screenshots. This isn't the same implementation as Google Play movies, so we can't compare speed with this library to speed of Google Play Movies.

**Comment by AndroidDeveloperLB** [comment]
oh ok.

**Comment by rubensousa** [comment]
@AndroidDeveloperLB, did you think the first screenshot was from this sample?

**Comment by AndroidDeveloperLB** [comment]
@rubensousa I thought that it shows how well the library can perform. I'm still not sure about this, because it doesn't handle a local video file yet. Only from the Internet, which could cause it to be slow, because it needs to fetch the thumbnail from a video.

**Comment by rubensousa** [comment]
I'll try to add local video support this week.

**Comment by rubensousa** [comment]
Finally had time to this. @AndroidDeveloperLB, can you check the sample again?
It was done in commit: https://github.com/rubensousa/PreviewSeekBar/commit/e3f6db2d6651136e3c1bb7949b64b28334464f1d

**Comment by AndroidDeveloperLB** [comment]
seems to work, but for some reason it couldn't open many mp4 files (all WhatsApp videos went gray). The one I created from the camera was ok.
BTW, the "toggle" doesn't seem to work well. Usually it appears and disappears right away.

**Comment by rubensousa** [comment]
I only tested videos from the camera and screen recordings. I'll take a look at the toggle issue
