### ISSUE TITLE
setPreviewColorTint does not work

### ISSUE THREAD

**Issue by Angelk90** [rubensousa/PreviewSeekBar#21]
@rubensousa : 
I'm trying to set it, but it does not find the method.
```
         previewTimeBar = playerView.findViewById (R.id.exo_progress);
         previewTimeBar.setPreviewColorTint (R.color.colorPrimary);
```

**Comment by rubensousa** [comment]
What's the issue exactly? Do you get an exception?

**Comment by Angelk90** [comment]
@rubensousa : The method is not found:
error: can not find symbol method setPreviewColorTint (int)

**Comment by rubensousa** [comment]
Please, update to 2.0.0 and 2.8.1.0. You're not using the latest version, that's why that method isn't found.
Check the Readme again. I'm closing this.

**Comment by Angelk90** [comment]
@rubensousa : 
I have updated to the latest version, I tried this way:
`         previewTimeBar.setPreviewColorTint (Color.parseColor ("# 00FF00"));
`
But it gives me the following error:
                                                  `  java.lang.RuntimeException: Unable to start activity ComponentInfo {com.exoplayer / com.exoplayer.SimpleVideoStream}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.view.View.getBackground ( ) 'on a null object reference`
