### ISSUE TITLE
Unable to import project

### ISSUE THREAD

**Issue by Arunkarthicknallasami** [rubensousa/PreviewSeekBar#24]
Error in gradle while importing project. using Android studio 3.1.3

**Comment by Arunkarthicknallasami** [comment]
okay will check again

**Comment by rubensousa** [comment]
What error message did you get?

**Comment by Arunkarthicknallasami** [comment]
Well it did not sync in my android studio will keep you posted on the error soon

**Comment by SarveshVerma94** [comment]
Unable to import project
