### ISSUE TITLE
Can I use it with youtube player?

### ISSUE THREAD

**Issue by NehaKushwah993** [rubensousa/PreviewSeekBar#25]

**Comment by rubensousa** [comment]
If you're talking about the player from the youtube sdk, no, since you can't change the layout AFAIK.

**Comment by NehaKushwah993** [comment]
Ok.. I found another solution, used MetaDataRetriever I pass URL and it gives me thumbnail of particular duration.

**Comment by MahdiPishguy** [comment]
@NehaKushwah993 could you help me how can i implementing that? Thanks

**Comment by NehaKushwah993** [comment]
@MahdiPishguy Hi, Do you still need solution?

**Comment by MahdiPishguy** [comment]
> 
> 
> @MahdiPishguy Hi, Do you still need solution?

i switched on `flutter`

**Comment by NehaKushwah993** [comment]
ok let me know if you need solution I will upload it on github.

**Comment by MahdiPishguy** [comment]
> 
> 
> ok let me know if you need solution I will upload it on github.

sure :+1:
