### ISSUE TITLE
Sizes of each thumbnail

### ISSUE THREAD

**Issue by ArcherEmiya05** [rubensousa/PreviewSeekBar#26]
What is the size of each thumbnail so that it will fit in the preview, I tried to use this sample https://jwsupport.cdn.prismic.io/jwsupport/f39cd28a5474fcd4d1aee96d20f0452a945890f8_tooltipthumbs-sprite.jpg and it doesn't fit in some scene.

**Comment by rubensousa** [comment]
The size shouldn't matter. If you're using the GlideTransformation as in the sample, you just need to change the number of lines and columns expected. If this varies, you'll need to take into account the size and hardcode it yourself there.

**Comment by ArcherEmiya05** [comment]
Is there any way to produce a preview thumbnail same with the thumbnail in the demo?

**Comment by rubensousa** [comment]
I'm not aware of any methods to perform this locally in the device. Sorry for the late reply, but this type of questions belong to StackOverflow.

**Comment by ArcherEmiya05** [comment]
I know this is an old question but I just want to know what do you mean by 'the size shouldn't matter' because I assume that I do no longer need to change any from the given sample regardless of the size of the preview thumbnail being use. I just literally follow your code and use the above image sample and it does not really fit.


 ```
@Override
    public void loadPreview(long currentPosition, long max) {
        player.setPlayWhenReady(false);
        GlideApp.with(this.context)
                .load(thumbnailsUrl)
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .transform(new GlideThumbnail(currentPosition))
                .into(imageView);
    }
```

**Comment by ArcherEmiya05** [comment]
I know this is an old question but I just want to know what do you mean by 'the size shouldn't matter' because with that words I assumed that I no longer need to change any from the given sample code regardless of what size of the preview thumbnail is being use. I just literally follow your code and use the above image sample and it does not fit.


 ```
@Override
    public void loadPreview(long currentPosition, long max) {
        player.setPlayWhenReady(false);
        GlideApp.with(this.context)
                .load(thumbnailsUrl)
                .override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)
                .transform(new GlideThumbnail(currentPosition))
                .into(imageView);
    }
```

**Comment by ArcherEmiya05** [comment]
So we could say that the size does matter right?
