### ISSUE TITLE
setOnSeekBarChangeListener does not work?

### ISSUE THREAD

**Issue by yeahman45** [rubensousa/PreviewSeekBar#31]
I have added a listerner with setOnSeekBarChangeListener but it does not seem to work.
It's not implemented yet?

**Comment by rubensousa** [comment]
You need to use OnPreviewChangeListener:

https://github.com/rubensousa/PreviewSeekBar/blob/0574a2c7469ee017dc9f50a496038fe946336122/previewseekbar/src/main/java/com/github/rubensousa/previewseekbar/PreviewView.java#L52
