### ISSUE TITLE
Unable to resolve getDefaultScrubberColor method in PreviewTimeBar

### ISSUE THREAD

**Issue by TwistedMetalGear** [rubensousa/PreviewSeekBar#32]
The PreviewTimeBar class makes a call to getDefaultScrubberColor but it seems like that method no longer exists in recent versions of ExoPlayer.

**Comment by rubensousa** [comment]
Yes, I'm aware. The exoplayer module needs to be updated. I'm working on this at the moment and will release a new version soon
