### ISSUE TITLE
Return type json what should I do?

### ISSUE THREAD

**Issue by halilozel1903** [rubensousa/PreviewSeekBar#34]
Hello,

I tried to compare it to its example, but it was not successful.

http://vod.sportstv.com.tr/39028754-454C-40BA-B253-FAF6C7E7B2B8/thumbnails/thumbnail.json

My data returns as json. I have more than one jpg file in json. How can I use them ? Help me please.

**Comment by rubensousa** [comment]
Please use StackOverflow for this type of questions. This is a problem specific for your app. You need to parse that json yourself.
