### ISSUE TITLE
Issue: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by PriyankaKamthe** [rubensousa/PreviewSeekBar#4]
When I run app on device with API 23 everything works nicely but whenever I tried to run app on device with API 19 Its gets crashed.
in logcat showing following error;

`java.lang.NoSuchMethodError: com.github.rubensousa.previewseekbar.PreviewSeekBar.getThumbTintList
`

Kindly provide solution to handle this issue.

**Comment by rubensousa** [comment]
Fixed in 0.3
