### ISSUE TITLE
Migrate away from jcenter.

### ISSUE THREAD

**Issue by snehilrx** [rubensousa/PreviewSeekBar#42]
Getting the following error while uisng this library. 
Could not find com.github.rubensousa:previewseekbar:3.0.0.
Required by:
    project :app

**Comment by anukools** [comment]
same issue. Any updates ?

**Comment by rubensousa** [comment]
Sorry for not replying any sooner, I will try to take care of this in the weekend

**Comment by rubensousa** [comment]
Released 3.1.0 in mavenCentral:  https://github.com/rubensousa/PreviewSeekBar/pull/44
