### ISSUE TITLE
Failed to resolve: com.github.rubensousa:previewseekbar:3.0.0 

### ISSUE THREAD

**Issue by PongPloy2016** [rubensousa/PreviewSeekBar#55]
Failed to resolve: com.github.rubensousa:previewseekbar:3.0.0
Show in Project Structure dialog
Show Details
Affected Modules: app
 
![Screenshot 2567-08-13 at 11 10 53](https://github.com/user-attachments/assets/6dc15629-037b-48a1-898f-497980c6fc09)

**Comment by rubensousa** [comment]
Please use `3.1.1`. That version was only available in jCenter, which was shutdown
