### ISSUE TITLE
PreviewSeekBar cannot be cast to com.google.android.exoplayer2.ui.TimeBar [Exoplayer 2.4.0]

### ISSUE THREAD

**Issue by Khoosham** [rubensousa/PreviewSeekBar#9]
Getting the following error as from exoplayer 2.4.0. i think they have change the control from a seekbar to a timebar ? The code was working well on Exoplayer 2.3.1

E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: android.view.InflateException: Binary XML file line #10: Error inflating class com.google.android.exoplayer2.ui.SimpleExoPlayerView
com.github.rubensousa.previewseekbar.PreviewSeekBar cannot be cast to com.google.android.exoplayer2.ui.TimeBar

these might help you
https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/DefaultTimeBar.html
https://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/ui/TimeBar.OnScrubListener.html

Any fix plz ?

**Comment by rubensousa** [comment]
I'll need to implement the TimeBar interface in PreviewSeekBar. If you want to help, please do and send a PR. I don't have much time right now.

**Comment by mdtuyen** [comment]
Exoplayer < 2.4 have bug outofmemory, we need upgrage library

**Comment by rubensousa** [comment]
Fixed on 1.0. Sorry for the delay

**Comment by Khoosham** [comment]
Thanks a lot @rubensousa 👍
